In [1]:
import numpy as np

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
training_data=pd.read_csv('Google_Stock_Price_Train.csv')

In [4]:
training_data.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [5]:
training_data=training_data.iloc[:,1:2].values

In [6]:
training_data

array([[ 325.25],
       [ 331.27],
       [ 329.83],
       ..., 
       [ 793.7 ],
       [ 783.33],
       [ 782.75]])

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
sc=MinMaxScaler()

In [9]:
training_data=sc.fit_transform(training_data)

In [10]:
type(training_data)

numpy.ndarray

In [11]:
training_data

array([[ 0.08581368],
       [ 0.09701243],
       [ 0.09433366],
       ..., 
       [ 0.95725128],
       [ 0.93796041],
       [ 0.93688146]])

In [12]:
X_train=training_data[0:1257]

In [13]:
y_train=training_data[1:1258]

In [14]:
y_train

array([[ 0.09701243],
       [ 0.09433366],
       [ 0.09156187],
       ..., 
       [ 0.95725128],
       [ 0.93796041],
       [ 0.93688146]])

In [15]:
#reshaping


In [16]:
X_train=np.reshape(X_train,(1257,1,1))

In [17]:
from keras.models import Sequential

Using TensorFlow backend.


In [18]:
from keras.layers import Dense

In [19]:
from keras.layers import LSTM 

In [20]:
regressor=Sequential()

In [21]:
regressor.add(LSTM(units=4,activation='sigmoid',input_shape=(None,1)))

In [22]:
regressor.add(Dense(units=1))

In [23]:
regressor.compile(optimizer='adam',loss='mean_squared_error')

In [24]:
regressor.fit(X_train,y_train,batch_size=32,epochs=300)

Epoch 1/300
1257/1257 [==============================] - 1s 867us/step - loss: 0.1541
Epoch 2/300
1257/1257 [==============================] - 0s 219us/step - loss: 0.1073
Epoch 3/300
1257/1257 [==============================] - 0s 238us/step - loss: 0.0839
Epoch 4/300
1257/1257 [==============================] - 0s 282us/step - loss: 0.0734
Epoch 5/300
1257/1257 [==============================] - 1s 413us/step - loss: 0.0690
Epoch 6/300
1257/1257 [==============================] - 0s 217us/step - loss: 0.0669
Epoch 7/300
1257/1257 [==============================] - 0s 237us/step - loss: 0.0655
Epoch 8/300
1257/1257 [==============================] - 0s 214us/step - loss: 0.0640
Epoch 9/300
1257/1257 [==============================] - 0s 232us/step - loss: 0.0626
Epoch 10/300
1257/1257 [==============================] - 0s 238us/step - loss: 0.0611
Epoch 11/300
1257/1257 [==============================] - 0s 205us/step - loss: 0.0595
Epoch 12/300
1257/1257 [============================

1257/1257 [==============================] - 0s 271us/step - loss: 2.4702e-04
Epoch 183/300
1257/1257 [==============================] - 0s 227us/step - loss: 2.5115e-04
Epoch 184/300
1257/1257 [==============================] - 0s 197us/step - loss: 2.4814e-04
Epoch 185/300
1257/1257 [==============================] - 0s 253us/step - loss: 2.5732e-04
Epoch 186/300
1257/1257 [==============================] - 0s 294us/step - loss: 2.4856e-04
Epoch 187/300
1257/1257 [==============================] - 0s 205us/step - loss: 2.4820e-04
Epoch 188/300
1257/1257 [==============================] - 0s 267us/step - loss: 2.4904e-04
Epoch 189/300
1257/1257 [==============================] - 0s 314us/step - loss: 2.4723e-04
Epoch 190/300
1257/1257 [==============================] - 0s 228us/step - loss: 2.4740e-04
Epoch 191/300
1257/1257 [==============================] - 0s 308us/step - loss: 2.4660e-04
Epoch 192/300
1257/1257 [==============================] - 0s 224us/step - loss: 2.4811e-04
Ep

In [19]:
test_data=pd.read_csv('Google_Stock_Price_Test.csv')

In [20]:
real_price=test_data.iloc[:,1:2].values

In [21]:
my=np.array([[849]])

In [22]:
my=sc.transform(my)

In [23]:
my=np.reshape(my,(1,1,1))

In [24]:
pred=regressor.predict(my)

In [25]:
pred=sc.inverse_transform(pred)

In [26]:
pred

array([[ 840.88360596]], dtype=float32)

In [27]:
real_price

array([[ 778.81],
       [ 788.36],
       [ 786.08],
       [ 795.26],
       [ 806.4 ],
       [ 807.86],
       [ 805.  ],
       [ 807.14],
       [ 807.48],
       [ 807.08],
       [ 805.81],
       [ 805.12],
       [ 806.91],
       [ 807.25],
       [ 822.3 ],
       [ 829.62],
       [ 837.81],
       [ 834.71],
       [ 814.66],
       [ 796.86]])

In [28]:
inputs=real_price

In [29]:
inputs=sc.transform(inputs)

In [30]:
inputs=np.reshape(inputs,(20,1,1))

In [31]:
predict_price=regressor.predict(inputs)

In [32]:
predict_price=sc.inverse_transform(predict_price)

In [33]:
predict_price

array([[ 776.65447998],
       [ 785.45935059],
       [ 783.35919189],
       [ 791.80804443],
       [ 802.034729  ],
       [ 803.37280273],
       [ 800.7510376 ],
       [ 802.71307373],
       [ 803.02471924],
       [ 802.65808105],
       [ 801.49383545],
       [ 800.86102295],
       [ 802.50219727],
       [ 802.81384277],
       [ 816.58221436],
       [ 823.26031494],
       [ 830.71801758],
       [ 827.89703369],
       [ 809.59924316],
       [ 793.27850342]], dtype=float32)

In [1]:
plt.figure(figsize=(12,7))
plt.plot(real_price,color='red',label='Real price')
plt.plot(predict_price,color='blue',label='Predict price')
plt.title('Google stock price predctions')
plt.xlabel('Time')
plt.ylabel('Stock price')

NameError: name 'plt' is not defined

In [17]:
from keras.models import load_model

Using TensorFlow backend.


In [36]:
regressor.save('newstock.h5')

In [18]:
regressor=load_model('newstock.h5')