In [1]:
R = [

     [5,3,0,1],

     [4,0,0,1],

     [1,1,0,5],

     [1,0,0,4],

     [0,1,5,4],

    ]

In [2]:
R

[[5, 3, 0, 1], [4, 0, 0, 1], [1, 1, 0, 5], [1, 0, 0, 4], [0, 1, 5, 4]]

In [3]:
import numpy as np

In [4]:
R=np.array(R)

In [5]:
R

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [6]:
N=len(R)

In [7]:
M=len(R[0])
K=2

In [8]:
P = np.random.rand(N,K)

Q = np.random.rand(M,K)


In [9]:
P

array([[ 0.85094466,  0.34710397],
       [ 0.63696275,  0.68437349],
       [ 0.87891507,  0.41031478],
       [ 0.96315487,  0.73473368],
       [ 0.30041052,  0.22037866]])

In [10]:
Q

array([[ 0.33669717,  0.20166797],
       [ 0.5535234 ,  0.20938009],
       [ 0.15773599,  0.07869496],
       [ 0.28692555,  0.89149493]])

In [11]:
Q.T

array([[ 0.33669717,  0.5535234 ,  0.15773599,  0.28692555],
       [ 0.20166797,  0.20938009,  0.07869496,  0.89149493]])

In [17]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):

    Q = Q.T

    for step in range(steps):

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])

                    for k in range(K):

                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])

                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = np.dot(P,Q)
        print(eR)

        e = 0

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))

        if e < 0.001:

            break

    return P, Q.T


In [18]:
nP, nQ = matrix_factorization(R, P, Q, K)

nR = np.dot(nP, nQ.T)


[[ 0.36393632  0.54751425  0.16335703  0.56278968]
 [ 0.35930105  0.49861717  0.1559046   0.80093505]
 [ 0.38650877  0.57613547  0.17280505  0.6289265 ]
 [ 0.4816342   0.69068393  0.21184364  0.94314742]
 [ 0.1494467   0.21495341  0.06581522  0.28890226]]
[[ 0.36766455  0.54943508  0.16427412  0.56740325]
 [ 0.36271756  0.49999827  0.15669971  0.80497337]
 [ 0.39044054  0.57800737  0.17375343  0.634419  ]
 [ 0.48622739  0.69254922  0.21290239  0.94904845]
 [ 0.15139416  0.21622777  0.0663659   0.2920465 ]]
[[ 0.37140301  0.55136319  0.16519696  0.57202907]
 [ 0.36613801  0.5013837   0.15749962  0.80901767]
 [ 0.39438245  0.57988597  0.17470784  0.63992329]
 [ 0.4908259   0.69441918  0.21396715  0.95495604]
 [ 0.15335467  0.21750966  0.06692143  0.29520687]]
[[ 0.37515172  0.55329857  0.16612555  0.57666716]
 [ 0.3695624   0.50277344  0.15830435  0.81306797]
 [ 0.39833453  0.58177128  0.17566832  0.64543938]
 [ 0.49542973  0.69629378  0.21503793  0.96087018]
 [ 0.15532826  0.21879907  0

[[ 1.32176383  1.06578113  0.50873162  1.70807437]
 [ 1.11677684  0.84622421  0.44056863  1.69769104]
 [ 1.36739506  1.06518532  0.53369002  1.94239473]
 [ 1.47802179  1.12913727  0.58126327  2.20377302]
 [ 0.84471271  0.63777404  0.33369359  1.2948791 ]]
[[ 1.3269132   1.06861173  0.51128126  1.7138827 ]
 [ 1.12039076  0.84800253  0.44258509  1.70182695]
 [ 1.37246365  1.06773673  0.53635981  1.94892089]
 [ 1.48257408  1.13121321  0.58383747  2.20936523]
 [ 0.84936018  0.64049825  0.33599483  1.30124453]]
[[ 1.33206119  1.07144164  0.51383942  1.71968403]
 [ 1.12399995  0.84977914  0.44460741  1.70595444]
 [ 1.377528    1.07028567  0.53903844  1.95543875]
 [ 1.48711746  1.13328504  0.58641865  2.21494393]
 [ 0.85401589  0.64322661  0.33830764  1.30761833]]
[[ 1.33720768  1.07427079  0.5164061   1.7254782 ]
 [ 1.12760435  0.85155401  0.44663559  1.71007342]
 [ 1.38258799  1.07283208  0.54172589  1.96194818]
 [ 1.49165185  1.1353527   0.58900676  2.22050903]
 [ 0.85867974  0.64595907  0

 [ 1.65964801  1.10559385  0.87246742  2.37034013]]
[[ 2.09895983  1.48952378  1.02996686  2.49147184]
 [ 1.62181518  1.09656473  0.84046811  2.2238406 ]
 [ 2.08479976  1.41478576  1.07614401  2.83020963]
 [ 2.07015573  1.38929004  1.08136185  2.89583965]
 [ 1.66452132  1.10831458  0.87666352  2.37652322]]
[[ 2.10293126  1.49163292  1.03355287  2.49474662]
 [ 1.6241875   1.09771536  0.84316205  2.22589013]
 [ 2.08809648  1.41626432  1.07984734  2.83406475]
 [ 2.07260263  1.39023767  1.08465793  2.89844691]
 [ 1.66939016  1.11103148  0.88086959  2.38269747]]
[[ 2.10689293  1.49373567  1.03714213  2.49800227]
 [ 1.6265518   1.09886131  0.84585792  2.22792612]
 [ 2.09137943  1.41773418  1.0835536   2.83790093]
 [ 2.07503614  1.39117745  1.08795538  2.90103622]
 [ 1.67425447  1.11374451  0.8850856   2.38886281]]
[[ 2.11084485  1.49583203  1.0407346   2.50123882]
 [ 1.6289081   1.10000259  0.84855571  2.22994859]
 [ 2.0946486   1.41919535  1.08726273  2.84171818]
 [ 2.0774563   1.3921094   

 [ 2.55292927  1.56436091  1.93487957  3.44356482]]
[[ 2.76697932  1.81181086  1.81868367  2.80618813]
 [ 1.99036309  1.25412454  1.4265978   2.40767182]
 [ 2.50975074  1.54761335  1.88019858  3.3032998 ]
 [ 2.34260765  1.43713137  1.77283579  3.14199716]
 [ 2.55622502  1.56580925  1.940206    3.44727617]]
[[ 2.76946944  1.81283094  1.82220761  2.80615614]
 [ 1.99164081  1.25455185  1.42920893  2.40760687]
 [ 2.51061777  1.5474948   1.88374704  3.30430464]
 [ 2.34295624  1.43677183  1.77579069  3.14215809]
 [ 2.55951231  1.56725106  1.94553243  3.4509761 ]]
[[ 2.77195639  1.81384814  1.82572853  2.80611356]
 [ 1.99291654  1.25497753  1.43181791  2.40753589]
 [ 2.51147671  1.54737092  1.88729213  3.30530297]
 [ 2.34329861  1.43640837  1.77874195  3.14231418]
 [ 2.56279114  1.56868634  1.95085882  3.45466462]]
[[ 2.77444022  1.81486247  1.82924641  2.80606045]
 [ 1.9941903   1.2554016   1.43442475  2.4074589 ]
 [ 2.51232756  1.54724173  1.89083384  3.30629484]
 [ 2.3436348   1.436041    

 [ 3.05725434  1.73807126  2.97253739  3.99533286]]
[[ 3.25096719  1.9883949   2.46364037  2.62430899]
 [ 2.24006953  1.32762611  1.90875471  2.29793728]
 [ 2.54600875  1.43694771  2.52746453  3.44188309]
 [ 2.30965628  1.30284837  2.29633332  3.13047884]
 [ 3.05888389  1.73838904  2.97704066  3.99712231]]
[[ 3.25331614  1.98919831  2.4663209   2.62275706]
 [ 2.2413252   1.32799386  1.91079022  2.29704408]
 [ 2.54559082  1.43609756  2.53016798  3.44249714]
 [ 2.30907371  1.30199258  2.29844362  3.1304266 ]
 [ 3.06050603  1.7387027   2.981537    3.99890471]]
[[ 3.25566603  1.99000202  2.46899682  2.62120013]
 [ 2.24258208  1.32836235  1.91282264  2.29614815]
 [ 2.54516787  1.43524527  2.53286719  3.44311272]
 [ 2.30848765  1.30113552  2.30054986  3.13037602]
 [ 3.06212078  1.73901226  2.98602639  4.00068008]]
[[ 3.25801687  1.99080604  2.47166814  2.61963822]
 [ 2.24384016  1.32873157  1.91485198  2.2952495 ]
 [ 2.54473988  1.43439086  2.53556218  3.44372985]
 [ 2.30789809  1.30027721  

 [ 3.25321448  1.73597769  3.75306693  4.24634654]]
[[ 3.76801039  2.17017678  2.92890008  2.21280907]
 [ 2.53679669  1.42737468  2.27110743  2.05956656]
 [ 2.35764445  1.22528903  3.01038782  3.62724671]
 [ 2.11717819  1.10529974  2.65908089  3.17300066]
 [ 3.25353321  1.73573426  3.75597719  4.24707062]]
[[ 3.77056495  2.1711121   2.93067613  2.21055351]
 [ 2.53837734  1.42797219  2.27254072  2.05822767]
 [ 2.35631601  1.22418212  3.01232717  3.62846278]
 [ 2.11595852  1.10431469  2.66047049  3.17350555]
 [ 3.25384705  1.73548944  3.75888009  4.24779128]]
[[ 3.77311986  2.17204793  2.93244841  2.2082963 ]
 [ 2.53995945  1.42857084  2.27397149  2.05688727]
 [ 2.35498409  1.22307482  3.01426359  3.62968216]
 [ 2.11473637  1.10332958  2.66185739  3.17401339]
 [ 3.254156    1.73524327  3.76177565  4.24850854]]
[[ 3.7756751   2.17298427  2.93421692  2.20603746]
 [ 2.54154302  1.42917064  2.27539975  2.05554535]
 [ 2.3536487   1.22196713  3.01619711  3.63090484]
 [ 2.11351176  1.10234441  

 [ 3.2322921   1.66654719  4.22572179  4.33914926]]
[[ 4.30017641  2.37262439  3.23434053  1.72186434]
 [ 2.89704126  1.57572501  2.52783649  1.75136881]
 [ 2.01536627  0.99127192  3.36931993  3.94884662]
 [ 1.81429099  0.90069158  2.90540556  3.33830886]
 [ 3.23187849  1.66619479  4.22731593  4.33934905]]
[[ 4.30248049  2.37353149  3.23547089  1.71967191]
 [ 2.89876124  1.5764804   2.52883482  1.74989671]
 [ 2.01361011  0.99024692  3.37077664  3.95054351]
 [ 1.81275996  0.89980035  2.90636097  3.33928108]
 [ 3.23146287  1.66584252  4.22890527  4.3395471 ]]
[[ 4.30478182  2.37443778  3.236599    1.71748169]
 [ 2.90048084  1.57723599  2.52983159  1.74842503]
 [ 2.01185368  0.98922305  3.37223166  3.95224111]
 [ 1.81122869  0.89891005  2.90731494  3.34025436]
 [ 3.23104525  1.66549038  4.23048982  4.33974342]]
[[ 4.30708038  2.37534323  3.23772486  1.71529368]
 [ 2.90220007  1.5779918   2.5308268   1.74695377]
 [ 2.01009699  0.9882003   3.37368497  3.95393942]
 [ 1.80969721  0.89802067  

 [ 3.14707199  1.61351556  4.4288753   4.3518096 ]]
[[ 4.62815733  2.50482149  3.39154255  1.40608383]
 [ 3.16261967  1.69672508  2.67110619  1.52601713]
 [ 1.73978096  0.84407812  3.58429945  4.22062334]
 [ 1.57283831  0.77141011  3.04317412  3.50037634]
 [ 3.14646619  1.61321867  4.42985019  4.35178247]]
[[ 4.62988824  2.50554003  3.3923878   1.40440012]
 [ 3.16416027  1.6974535   2.67190144  1.52472661]
 [ 1.73817522  0.84329303  3.58552447  4.22223968]
 [ 1.57141672  0.77070843  3.04394344  3.50136998]
 [ 3.14585988  1.61292225  4.43082213  4.35175422]]
[[ 4.63161508  2.50625719  3.3932317   1.40272021]
 [ 3.16569913  1.69818142  2.6726957   1.52343782]
 [ 1.73657143  0.84250969  3.58674825  4.22385445]
 [ 1.5699966   0.7700081   3.04471185  3.50236293]
 [ 3.14525307  1.61262631  4.4317911   4.35172486]]
[[ 4.63333785  2.50697295  3.39407427  1.40104412]
 [ 3.16723624  1.69890885  2.67348896  1.52215075]
 [ 1.73496962  0.84172809  3.58797082  4.22546763]
 [ 1.56857795  0.76930913  

[[ 4.89971606  2.62363413  3.54275874  1.14013566]
 [ 3.43741641  1.83315581  2.81723393  1.30156909]
 [ 1.45965704  0.71954349  3.81324789  4.50971652]
 [ 1.31894851  0.65603458  3.18549541  3.68160276]
 [ 3.01829837  1.56225478  4.57975779  4.32734221]]
[[ 4.90064159  2.624076    3.54340258  1.13922319]
 [ 3.43852715  1.83374144  2.81787033  1.30069355]
 [ 1.45857014  0.71911473  3.81425518  4.51087322]
 [ 1.31793037  0.65561392  3.18611973  3.68233893]
 [ 3.01768651  1.56205406  4.58029093  4.32715449]]
[[ 4.90156371  2.6245167   3.54404573  1.13831403]
 [ 3.43963571  1.83432628  2.81850614  1.29982006]
 [ 1.45748592  0.71868754  3.81526156  4.51202741]
 [ 1.3169144   0.65519454  3.18674351  3.68307357]
 [ 3.01707492  1.56185373  4.58082263  4.32696631]]
[[ 4.90248242  2.62495623  3.54468817  1.13740819]
 [ 3.4407421   1.83491034  2.81914136  1.29894863]
 [ 1.4564044   0.71826192  3.81626703  4.5131791 ]
 [ 1.31590058  0.65477641  3.18736674  3.68380668]
 [ 3.0164636   1.56165381  4

[[ 5.03252901  2.69622043  3.66813582  1.00849765]
 [ 3.63012202  1.94211553  2.94251416  1.15622698]
 [ 1.28244605  0.65851881  4.01130326  4.70488193]
 [ 1.14636035  0.59120376  3.30956715  3.8064876 ]
 [ 2.89369485  1.52656136  4.66845916  4.2799471 ]]
[[ 5.03288788  2.69646959  3.66866169  1.00813822]
 [ 3.6308145   1.94254353  2.94304351  1.15573536]
 [ 1.28186413  0.65836019  4.0121366   4.70555434]
 [ 1.1457628   0.59100853  3.31009816  3.80691924]
 [ 2.89315518  1.52642428  4.66877397  4.27971167]]
[[ 5.0332449   2.69671812  3.66918712  1.0077806 ]
 [ 3.63150536  1.94297089  2.94357245  1.15524518]
 [ 1.28128408  0.65820249  4.01296922  4.7062249 ]
 [ 1.14516689  0.59081412  3.31062883  3.80734969]
 [ 2.89261583  1.52628739  4.6690881   4.27947621]]
[[ 5.03360008  2.69696603  3.66971212  1.00742477]
 [ 3.6321946   1.94339762  2.94410096  1.15475642]
 [ 1.2807059   0.65804571  4.01380115  4.7068936 ]
 [ 1.1445726   0.59062052  3.31115915  3.80777895]
 [ 2.89207682  1.52615069  4

[[ 5.0766843   2.73879329  3.7730437   0.96328124]
 [ 3.74774744  2.02169443  3.04829615  1.0776929 ]
 [ 1.19258428  0.6414058   4.17696547  4.81398464]
 [ 1.04942775  0.56456698  3.41759332  3.87645941]
 [ 2.78358722  1.50010881  4.72410519  4.23014004]]
[[ 5.07676982  2.73894875  3.77348821  0.96318688]
 [ 3.74816099  2.02200695  3.04874446  1.07743846]
 [ 1.19230684  0.6413894   4.17766423  4.81434576]
 [ 1.04910846  0.56450358  3.41806118  3.8766905 ]
 [ 2.78310835  1.49999739  4.72431462  4.22992303]]
[[ 5.07685457  2.73910392  3.77393239  0.96309327]
 [ 3.74857356  2.02231904  3.04919244  1.07718481]
 [ 1.19203038  0.64137343  4.17836245  4.81470583]
 [ 1.04879012  0.56444062  3.4185288   3.87692091]
 [ 2.78262971  1.49988603  4.7245237   4.22970618]]
[[ 5.07693854  2.73925883  3.77437625  0.96300039]
 [ 3.74898515  2.02263071  3.04964008  1.07693195]
 [ 1.1917549   0.64135788  4.17906013  4.81506486]
 [ 1.04847274  0.56437808  3.41899617  3.87715065]
 [ 2.78215129  1.49977473  4

[[ 5.08201301  2.76629801  3.85816766  0.95550071]
 [ 3.81541308  2.07808843  3.13403307  1.03896084]
 [ 1.15199066  0.6450103   4.31035318  4.87012358]
 [ 1.0004298   0.55892719  3.5091613   3.91231253]
 [ 2.68906659  1.47794811  4.76114335  4.18917217]]
[[ 5.08199557  2.76641463  3.85855137  0.95550348]
 [ 3.81566956  2.07832798  3.13441887  1.03882699]
 [ 1.15185709  0.64505344  4.31095307  4.87032349]
 [ 1.00025932  0.55892897  3.50958396  3.91243996]
 [ 2.6886253   1.47784262  4.7612979   4.1889927 ]]
[[ 5.08197783  2.76653113  3.85893482  0.95550652]
 [ 3.81592547  2.07856724  3.13480439  1.03869356]
 [ 1.15172398  0.64509675  4.31155254  4.87052284]
 [ 1.00008937  0.55893097  3.51000643  3.91256703]
 [ 2.68818416  1.47773715  4.76145224  4.18881342]]
[[ 5.08195982  2.7666475   3.85931799  0.95550981]
 [ 3.8161808   2.07880622  3.13518963  1.03856054]
 [ 1.15159134  0.64514025  4.31215158  4.87072163]
 [ 0.99991994  0.5589332   3.5104287   3.91269375]
 [ 2.68774317  1.47763168  4

 [ 2.61262511  1.45919307  4.78576191  4.16019053]]
[[ 5.07557123  2.78558559  3.92282995  0.95898325]
 [ 3.85339872  2.11686045  3.19894323  1.02052974]
 [ 1.13407887  0.65492237  4.41145383  4.8984299 ]
 [ 0.97696335  0.56218012  3.58185806  3.93035584]
 [ 2.61220661  1.45908745  4.78588559  4.16004405]]
[[ 5.07552222  2.78568606  3.92316969  0.9590141 ]
 [ 3.85357254  2.11705629  3.19928372  1.02045259]
 [ 1.13400564  0.65498699  4.4119856   4.89855295]
 [ 0.97686552  0.56221191  3.58224833  3.93043434]
 [ 2.61178823  1.45898182  4.78600913  4.15989775]]
[[ 5.07547312  2.78578647  3.92350919  0.95904502]
 [ 3.85374599  2.11725191  3.19962398  1.02037568]
 [ 1.13393265  0.65505168  4.41251703  4.89867567]
 [ 0.976768    0.56224382  3.58263843  3.93051265]
 [ 2.61136995  1.45887619  4.78613252  4.15975162]]
[[ 5.07542392  2.78588681  3.92384848  0.95907602]
 [ 3.85391908  2.11744734  3.199964    1.02029901]
 [ 1.13385989  0.65511645  4.41304811  4.89879808]
 [ 0.97667078  0.56227585  

[[ 5.06615155  2.8022185   3.9787114   0.96504761]
 [ 3.87888628  2.14811882  3.25487931  1.01007466]
 [ 1.12412799  0.66698578  4.49917017  4.91576512]
 [ 0.96383823  0.56925176  3.64735637  3.94144316]
 [ 2.54101043  1.44061877  4.8053922   4.13708972]]
[[ 5.06609461  2.80230982  3.97901472  0.96508433]
 [ 3.87900883  2.14828362  3.25518258  1.01002896]
 [ 1.12408357  0.66705847  4.49964813  4.91584488]
 [ 0.96378184  0.5692998   3.64771941  3.94149436]
 [ 2.54061014  1.44051213  4.80549381  4.13697153]]
[[ 5.06603765  2.80240109  3.97931785  0.96512106]
 [ 3.87913114  2.14844826  3.25548566  1.0099834 ]
 [ 1.12403927  0.66713118  4.50012581  4.91592445]
 [ 0.96372564  0.56934792  3.64808231  3.94154545]
 [ 2.54020995  1.44040548  4.8055953   4.13685348]]
[[ 5.06598069  2.80249232  3.97962078  0.96515779]
 [ 3.87925321  2.14861275  3.25578854  1.00993797]
 [ 1.12399507  0.66720392  4.50060321  4.91600383]
 [ 0.96366962  0.5693961   3.64844506  3.94159641]
 [ 2.53980986  1.44029883  4

[[ 5.05813672  2.81470123  4.0196473   0.97014476]
 [ 3.89407967  2.16994093  3.2957843   1.00479881]
 [ 1.11878244  0.67740841  4.56394319  4.92537589]
 [ 0.95745812  0.57661433  3.69714856  3.94763444]
 [ 2.48551293  1.42554665  4.81871367  4.1217999 ]]
[[ 5.05808066  2.81478711  4.01992498  0.97017975]
 [ 3.89417402  2.17008622  3.29606163  1.00476867]
 [ 1.11874992  0.67748313  4.56438468  4.92543378]
 [ 0.95742272  0.57667017  3.69749198  3.94767189]
 [ 2.485126    1.4254396   4.81880141  4.1217008 ]]
[[ 5.05802462  2.81487296  4.02020249  0.97021472]
 [ 3.89426819  2.17023139  3.29633879  1.00473862]
 [ 1.11871745  0.67755785  4.56482594  4.92549155]
 [ 0.95738744  0.57672606  3.69783527  3.94770927]
 [ 2.48473916  1.42533255  4.81888906  4.12160183]]
[[ 5.05796859  2.81495877  4.02047983  0.97024967]
 [ 3.8943622   2.17037644  3.29661578  1.00470866]
 [ 1.11868505  0.67763257  4.56526696  4.9255492 ]
 [ 0.95735227  0.57678199  3.69817842  3.94774657]
 [ 2.48435242  1.4252255   4

 [ 2.40333026  1.4022555   4.83595036  4.10286448]]
[[ 5.04647356  2.8327088   4.07662368  0.97714535]
 [ 3.91131588  2.19907199  3.35267538  0.9999204 ]
 [ 1.11273346  0.69377729  4.65534007  4.93557725]
 [ 0.95206774  0.58966672  3.76935089  3.95427465]
 [ 2.40296324  1.40214916  4.83602152  4.10278881]]
[[ 5.04642365  2.83278747  4.07686724  0.97717393]
 [ 3.91138119  2.19919377  3.35291858  0.99990454]
 [ 1.11270938  0.69385159  4.65573481  4.93561445]
 [ 0.952052    0.58972928  3.76966738  3.95429903]
 [ 2.40259631  1.40204283  4.83609261  4.10271324]]
[[ 5.04637377  2.83286611  4.07711065  0.97720248]
 [ 3.9114464   2.19931545  3.35316164  0.99988872]
 [ 1.11268532  0.69392589  4.65612935  4.93565158]
 [ 0.95203634  0.58979185  3.76998377  3.95432337]
 [ 2.40222948  1.4019365   4.83616363  4.10263776]]
[[ 5.04632393  2.83294472  4.07735392  0.977231  ]
 [ 3.9115115   2.19943705  3.35340456  0.99987295]
 [ 1.11266128  0.69400017  4.6565237   4.93568864]
 [ 0.95202073  0.58985445  

 [ 2.3542475   1.38787226  4.84506417  4.09336895]]
[[ 5.03999682  2.84312044  4.10849141  0.98073971]
 [ 3.91933923  2.21482513  3.38450584  0.99814191]
 [ 1.10962178  0.70380434  4.70734854  4.94006412]
 [ 0.95046102  0.59833313  3.81137554  3.95722487]
 [ 2.3538928   1.3877672   4.84512723  4.09330469]]
[[ 5.03995153  2.84319486  4.1087167   0.98076399]
 [ 3.9193924   2.21493524  3.38473096  0.99813132]
 [ 1.10959987  0.70387742  4.70771899  4.9400933 ]
 [ 0.95045273  0.59839785  3.81167715  3.95724411]
 [ 2.3535382   1.38766214  4.84519023  4.09324051]]
[[ 5.03990627  2.84326925  4.10894186  0.98078824]
 [ 3.9194455   2.21504527  3.38495595  0.99812077]
 [ 1.10957797  0.70395048  4.70808927  4.94012242]
 [ 0.95044448  0.59846257  3.81197866  3.95726332]
 [ 2.35318368  1.38755709  4.84525317  4.09317641]]
[[ 5.03986105  2.84334361  4.1091669   0.98081246]
 [ 3.91949851  2.21515522  3.38518081  0.99811024]
 [ 1.10955608  0.70402353  4.70845938  4.9401515 ]
 [ 0.95043628  0.59852732  

[[ 5.0306382   2.85908591  4.15615907  0.98547734]
 [ 3.92962428  2.23775119  3.43218197  0.99642364]
 [ 1.10488267  0.71995953  4.78675262  4.94556779]
 [ 0.9495487   0.61311019  3.87671373  3.96086537]
 [ 2.27638759  1.36447075  4.85806012  4.08058615]]
[[ 5.03060019  2.85915339  4.15635813  0.98549538]
 [ 3.92966351  2.23784541  3.4323813   0.99641843]
 [ 1.10486217  0.72002997  4.78708895  4.94558824]
 [ 0.94954818  0.6131765   3.87699329  3.96087892]
 [ 2.27605334  1.36436895  4.85811255  4.08053655]]
[[ 5.03056221  2.85922083  4.15655708  0.98551339]
 [ 3.92970268  2.23793956  3.43258053  0.99641325]
 [ 1.10484166  0.7201004   4.78742514  4.94560865]
 [ 0.94954768  0.61324281  3.87727275  3.96089245]
 [ 2.27571919  1.36426717  4.85816493  4.08048701]]
[[ 5.03052426  2.85928825  4.15675593  0.98553137]
 [ 3.92974181  2.23803365  3.43277965  0.99640808]
 [ 1.10482116  0.72017081  4.78776119  4.94562904]
 [ 0.94954721  0.61330912  3.87755213  3.96090596]
 [ 2.27538512  1.3641654   4

[[ 5.02459202  2.87011825  4.18852576  0.98821453]
 [ 3.93565302  2.25290803  3.46462666  0.99575727]
 [ 1.10142602  0.73175158  4.84203928  4.9486603 ]
 [ 0.94978211  0.62440385  3.92296163  3.96291388]
 [ 2.22085915  1.34742508  4.86642912  4.07288138]]
[[ 5.02455882  2.87018055  4.18870773  0.98822881]
 [ 3.93568505  2.25299232  3.46480928  0.99575447]
 [ 1.10140581  0.73181984  4.84235373  4.94867646]
 [ 0.94978515  0.62447029  3.9232263   3.96292457]
 [ 2.22054019  1.34732644  4.86647534  4.07284004]]
[[ 5.02452564  2.87024282  4.18888961  0.98824308]
 [ 3.93571705  2.25307656  3.4649918   0.99575168]
 [ 1.10138559  0.73188809  4.84266807  4.9486926 ]
 [ 0.94978821  0.62453672  3.9234909   3.96293524]
 [ 2.22022131  1.34722783  4.86652153  4.07279875]]
[[ 5.02449249  2.87030506  4.18907139  0.98825732]
 [ 3.93574901  2.25316075  3.46517424  0.99574891]
 [ 1.10136538  0.73195633  4.84298228  4.94870872]
 [ 0.94979129  0.62460315  3.92375541  3.96294591]
 [ 2.21990253  1.34712923  4

[[ 5.0181054   2.88266117  4.22508763  0.99084424]
 [ 3.94172685  2.26963582  3.50137359  0.99537619]
 [ 1.09715236  0.74592988  4.9061402   4.95166975]
 [ 0.95074953  0.6384296   3.97726908  3.96489975]
 [ 2.15522518  1.32697837  4.87555249  4.06498582]]
[[ 5.01807727  2.88271721  4.22525094  0.99085493]
 [ 3.94175247  2.26970959  3.50153799  0.99537524]
 [ 1.09713223  0.74599535  4.90643094  4.95168221]
 [ 0.95075539  0.63849535  3.97751695  3.96490794]
 [ 2.15492497  1.32688421  4.87559257  4.06495231]]
[[ 5.01804916  2.88277323  4.22541416  0.99086561]
 [ 3.94177807  2.26978331  3.50170231  0.99537429]
 [ 1.09711211  0.74606082  4.90672157  4.95169465]
 [ 0.95076126  0.6385611   3.97776475  3.96491612]
 [ 2.15462485  1.32679008  4.87563263  4.06491883]]
[[ 5.01802108  2.88282921  4.22557731  0.99087627]
 [ 3.94180364  2.26985698  3.50186655  0.99537336]
 [ 1.09709199  0.74612626  4.90701211  4.95170708]
 [ 0.95076714  0.63862684  3.97801248  3.9649243 ]
 [ 2.15432481  1.32669596  4

 [ 2.10657722  1.31165603  4.88187804  4.05982439]]
[[ 5.01369382  2.89162669  4.25126384  0.99244567]
 [ 3.94568427  2.28134844  3.52775778  0.99529709]
 [ 1.09379663  0.75668036  4.95330168  4.95356906]
 [ 0.95185235  0.64933052  4.01764866  3.96614506]
 [ 2.10629134  1.31156563  4.88191426  4.05979555]]
[[ 5.01366905  2.89167803  4.25141417  0.99245423]
 [ 3.94570618  2.28141505  3.52790951  0.99529703]
 [ 1.09377656  0.75674362  4.95357593  4.95357943]
 [ 0.95185961  0.64939525  4.01788445  3.96615185]
 [ 2.10600553  1.31147525  4.88195047  4.05976675]]
[[ 5.0136443   2.89172934  4.25156443  0.99246279]
 [ 3.94572807  2.28148162  3.52806116  0.99529698]
 [ 1.0937565   0.75680687  4.95385009  4.9535898 ]
 [ 0.95186688  0.64945998  4.01812017  3.96615862]
 [ 2.10571982  1.31138489  4.88198666  4.05973797]]
[[ 5.01361957  2.89178062  4.25171461  0.99247133]
 [ 3.94574994  2.28154815  3.52821273  0.99529694]
 [ 1.09373644  0.7568701   4.95412416  4.95360015]
 [ 0.95187416  0.64952471  

[[ 5.00995612  2.89949809  4.27440821  0.99368459]
 [ 3.94896018  2.29151213  3.551145    0.99533691]
 [ 1.09059464  0.76663269  4.99602459  4.95510223]
 [ 0.95309053  0.65959227  4.05450919  3.96714502]
 [ 2.061635    1.29739951  4.88745363  4.05548224]]
[[ 5.00993412  2.89954516  4.2745473   0.99369157]
 [ 3.94897931  2.29157264  3.55128572  0.99533742]
 [ 1.09057469  0.76669382  4.9962845   4.95511108]
 [ 0.95309869  0.65965576  4.05473421  3.96715078]
 [ 2.06136261  1.29731285  4.88748674  4.05545702]]
[[ 5.00991213  2.8995922   4.27468631  0.99369854]
 [ 3.94899842  2.29163312  3.55142638  0.99533794]
 [ 1.09055474  0.76675494  4.99654432  4.95511991]
 [ 0.95310685  0.65971924  4.05495916  3.96715653]
 [ 2.06109031  1.29722621  4.88751982  4.05543182]]
[[ 5.00989016  2.89963922  4.27482526  0.9937055 ]
 [ 3.94901751  2.29169356  3.55156697  0.99533846]
 [ 1.09053479  0.76681605  4.99680406  4.95512874]
 [ 0.95311502  0.65978271  4.05518405  3.96716228]
 [ 2.06081809  1.29713959  4

 [ 2.0126296   1.28176405  4.89329313  4.05113146]]
[[ 5.00612668  2.90781795  4.29916542  0.99484555]
 [ 3.95227046  2.30217265  3.57622807  0.99547526]
 [ 1.08690192  0.77777456  5.04293851  4.95661432]
 [ 0.95467488  0.67124601  4.09526877  3.96812843]
 [ 2.01237217  1.2816817   4.89332323  4.05110953]]
[[ 5.00610745  2.90786038  4.29929268  0.99485111]
 [ 3.95228702  2.30222686  3.5763572   0.9954762 ]
 [ 1.08688218  0.77783322  5.04318321  4.95662179]
 [ 0.9546837   0.67130779  4.09548211  3.96813329]
 [ 2.01211483  1.28159938  4.89335332  4.05108761]]
[[ 5.00608822  2.90790279  4.29941989  0.99485667]
 [ 3.95230356  2.30228104  3.57648626  0.99547714]
 [ 1.08686245  0.77789187  5.04342784  4.95662925]
 [ 0.95469253  0.67136955  4.09569538  3.96813814]
 [ 2.01185757  1.28151708  4.89338339  4.05106571]]
[[ 5.00606902  2.90794517  4.29954703  0.99486222]
 [ 3.95232009  2.30233519  3.57661527  0.99547808]
 [ 1.08684271  0.77795051  5.04367238  4.95663671]
 [ 0.95470135  0.6714313   

[[ 5.00209035  2.91685537  4.32656991  0.99595824]
 [ 3.955741    2.31370093  3.60407815  0.99572546]
 [ 1.08246346  0.79075151  5.09655301  4.95815961]
 [ 0.95673208  0.68500646  4.14218289  3.96913663]
 [ 1.95594925  1.2635871   4.89979876  4.04649952]]
[[ 5.00207395  2.91689263  4.32668429  0.99596254]
 [ 3.95575511  2.31374842  3.6041946   0.99572669]
 [ 1.08244412  0.79080717  5.0967809   4.95816581]
 [ 0.95674133  0.68506588  4.14238301  3.9691407 ]
 [ 1.95570939  1.26351     4.89982582  4.04648068]]
[[ 5.00205756  2.91692988  4.32679863  0.99596684]
 [ 3.95576922  2.31379588  3.60431098  0.99572793]
 [ 1.08242477  0.79086282  5.09700872  4.95817201]
 [ 0.95675058  0.68512528  4.14258308  3.96914477]
 [ 1.9554696   1.26343293  4.89985286  4.04646186]]
[[ 5.00204118  2.9169671   4.32691291  0.99597114]
 [ 3.95578331  2.31384332  3.60442732  0.99572917]
 [ 1.08240543  0.79091846  5.09723647  4.95817821]
 [ 0.95675983  0.68518467  4.14278309  3.96914883]
 [ 1.95522989  1.26335587  4

[[ 4.99963413  2.92248357  4.34399809  0.99658475]
 [ 3.9578596   2.320874    3.62183873  0.99593007]
 [ 1.07943383  0.79938411  5.13170597  4.95908382]
 [ 0.95820436  0.6942564   4.17312059  3.96974641]
 [ 1.91896533  1.25168439  4.90393086  4.0436607 ]]
[[ 4.99961942  2.92251757  4.34410437  0.9965884 ]
 [ 3.95787233  2.32091735  3.62194716  0.99593142]
 [ 1.07941484  0.79943771  5.13192311  4.95908934]
 [ 0.95821373  0.69431405  4.17331211  3.96975007]
 [ 1.91873703  1.25161083  4.90395614  4.04364355]]
[[ 4.99960471  2.92255155  4.3442106   0.99659204]
 [ 3.95788505  2.32096068  3.62205554  0.99593276]
 [ 1.07939585  0.79949129  5.13214018  4.95909485]
 [ 0.9582231   0.69437169  4.17350357  3.96975373]
 [ 1.9185088   1.25153729  4.9039814   4.04362642]]
[[ 4.99959002  2.92258552  4.34431679  0.99659568]
 [ 3.95789777  2.32100398  3.62216387  0.99593411]
 [ 1.07937686  0.79954487  5.13235718  4.95910035]
 [ 0.95823247  0.69442932  4.17369497  3.96975739]
 [ 1.91828065  1.25146378  4

 [ 1.88463942  1.24061343  4.90770348  4.04112868]]
[[ 4.99746882  2.92752325  4.35989779  0.99710896]
 [ 3.95974112  2.32730458  3.63807675  0.99614401]
 [ 1.07651946  0.80753762  5.16459116  4.95989367]
 [ 0.95965943  0.70305485  4.20218124  3.97028938]
 [ 1.88442191  1.24054322  4.90772722  4.04111291]]
[[ 4.99745557  2.9275543   4.35999671  0.99711209]
 [ 3.95975269  2.32734424  3.63817788  0.99614542]
 [ 1.07650086  0.80758922  5.16479839  4.95989862]
 [ 0.95966882  0.70311071  4.20236472  3.97029273]
 [ 1.88420448  1.24047303  4.90775095  4.04109715]]
[[ 4.99744234  2.92758533  4.36009559  0.99711522]
 [ 3.95976425  2.32738387  3.63827897  0.99614682]
 [ 1.07648226  0.8076408   5.16500556  4.95990356]
 [ 0.95967821  0.70316656  4.20254814  3.97029608]
 [ 1.88398711  1.24040286  4.90777467  4.0410814 ]]
[[ 4.99742911  2.92761634  4.36019442  0.99711835]
 [ 3.9597758   2.32742349  3.63838002  0.99614823]
 [ 1.07646367  0.80769238  5.16521266  4.95990851]
 [ 0.9596876   0.70322239  

[[ 4.99531667  2.93260382  4.37625817  0.9976072 ]
 [ 3.96163223  2.33380384  3.65482224  0.99638904]
 [ 1.07336107  0.81622522  5.19934109  4.9606987 ]
 [ 0.96127024  0.712489    4.23300717  3.97084186]
 [ 1.84801408  1.22878043  4.91167608  4.03851475]]
[[ 4.99530487  2.93263188  4.37634955  0.99760988]
 [ 3.96164268  2.33383979  3.65491587  0.99639047]
 [ 1.07334296  0.81627463  5.19953798  4.96070313]
 [ 0.96127956  0.71254282  4.23318216  3.97084494]
 [ 1.84780814  1.22871385  4.91169829  4.03850027]]
[[ 4.99529308  2.93265992  4.37644088  0.99761255]
 [ 3.96165312  2.33387573  3.65500946  0.99639191]
 [ 1.07332485  0.81632403  5.19973482  4.96070755]
 [ 0.96128889  0.71259663  4.2333571   3.97084802]
 [ 1.84760226  1.22864728  4.91172049  4.03848579]]
[[ 4.99528129  2.93268794  4.37653216  0.99761523]
 [ 3.96166355  2.33391164  3.65510301  0.99639335]
 [ 1.07330674  0.81637342  5.19993159  4.96071197]
 [ 0.96129821  0.71265043  4.23353199  3.9708511 ]
 [ 1.84739645  1.22858073  4

In [21]:
#Recommendations matrix
nR

array([[ 4.97975788,  2.9728992 ,  5.27623989,  1.00145142],
       [ 3.977918  ,  2.38775381,  4.3996657 ,  0.99941143],
       [ 1.03091607,  0.92467096,  5.50768724,  4.96946996],
       [ 0.98502363,  0.83355636,  4.54923193,  3.9789583 ],
       [ 1.42518398,  1.09226897,  4.9576006 ,  4.00492406]])