In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset=pd.read_csv('Churn_Modelling.csv')

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
X=dataset.iloc[:,3:13].values

In [8]:
y=dataset.iloc[:,13].values

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [10]:
label_x=LabelEncoder()

In [11]:
label_x2=LabelEncoder()

In [12]:
X[:,1]=label_x.fit_transform(X[:,1])

In [13]:
X[:,2]=label_x2.fit_transform(X[:,2])

In [14]:
one=OneHotEncoder(categorical_features=[1])

In [15]:
X=one.fit_transform(X).toarray()

In [16]:
X=X[:,1:]

In [17]:
X.shape

(10000, 11)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [21]:
X_train.shape

(7500, 11)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
sc=StandardScaler()

In [24]:
X_train=sc.fit_transform(X_train)

In [25]:
X_test=sc.transform(X_test)

In [22]:
import keras

Using TensorFlow backend.


In [23]:
from keras.models import Sequential

In [24]:
from keras.layers import Dense

In [25]:
#intializing the ANN
classifier=Sequential()

In [26]:
#first layer:
classifier.add(Dense(units=6,init='uniform',activation='relu',input_dim=11))

/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", input_dim=11, kernel_initializer="uniform")`
  


In [27]:
classifier.add(Dense(units=6,init='uniform',activation='relu'))

/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [28]:
classifier.add(Dense(units=1,init='uniform',activation='sigmoid'))

/home/dhama/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [29]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [30]:
classifier.fit(X_train,y_train,batch_size=10,epochs=150)

Epoch 1/150
7500/7500 [==============================] - 18s 2ms/step - loss: 0.4945 - acc: 0.7959
Epoch 2/150
7500/7500 [==============================] - 3s 406us/step - loss: 0.4286 - acc: 0.7963
Epoch 3/150
7500/7500 [==============================] - 3s 404us/step - loss: 0.4214 - acc: 0.8155
Epoch 4/150
7500/7500 [==============================] - 3s 404us/step - loss: 0.4142 - acc: 0.8307
Epoch 5/150
7500/7500 [==============================] - 3s 409us/step - loss: 0.4091 - acc: 0.8300
Epoch 6/150
7500/7500 [==============================] - 3s 425us/step - loss: 0.4065 - acc: 0.8332
Epoch 7/150
7500/7500 [==============================] - 3s 429us/step - loss: 0.4047 - acc: 0.8348
Epoch 8/150
7500/7500 [==============================] - 3s 439us/step - loss: 0.4025 - acc: 0.8335
Epoch 9/150
7500/7500 [==============================] - 3s 434us/step - loss: 0.4020 - acc: 0.8340
Epoch 10/150
7500/7500 [==============================] - 3s 425us/step - loss: 0.3999 - acc: 0.8356


7500/7500 [==============================] - 3s 397us/step - loss: 0.3373 - acc: 0.8633
Epoch 83/150
7500/7500 [==============================] - 3s 393us/step - loss: 0.3381 - acc: 0.8615
Epoch 84/150
7500/7500 [==============================] - 3s 388us/step - loss: 0.3369 - acc: 0.8620
Epoch 85/150
7500/7500 [==============================] - 3s 392us/step - loss: 0.3377 - acc: 0.8613
Epoch 86/150
7500/7500 [==============================] - 3s 389us/step - loss: 0.3374 - acc: 0.8621
Epoch 87/150
7500/7500 [==============================] - 3s 395us/step - loss: 0.3384 - acc: 0.8609
Epoch 88/150
7500/7500 [==============================] - 3s 392us/step - loss: 0.3372 - acc: 0.8612
Epoch 89/150
7500/7500 [==============================] - 3s 405us/step - loss: 0.3377 - acc: 0.8620
Epoch 90/150
7500/7500 [==============================] - 3s 392us/step - loss: 0.3367 - acc: 0.8611
Epoch 91/150
7500/7500 [==============================] - 3s 396us/step - loss: 0.3358 - acc: 0.8615
Epo

In [31]:
y_pred=classifier.predict(X_test)

In [32]:
y_pred=(y_pred>0.5)

In [33]:
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm=confusion_matrix(y_test,y_pred)

In [36]:
cm

array([[1819,  172],
       [ 200,  309]])

In [3]:

from keras.models import load_model

Using TensorFlow backend.


In [46]:
classifier.save('Ann.h5')

In [4]:
classifier=load_model('Ann.h5')  

In [26]:
new_pred=classifier.predict(sc.transform(np.array([[0.0,0,600,1,40,3,60000,2,1,1,50000]])))

In [27]:
new_pred=new_pred>0.5

In [28]:
new_pred

array([[False]], dtype=bool)