In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [127]:

dataset=pd.read_csv('train.csv')

In [128]:
dataset_2=pd.read_csv('test.csv')

In [129]:

dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [130]:
dataset['Embarked']=dataset['Embarked'].fillna(value='S')

In [131]:
dataset_2['Embarked']=dataset['Embarked'].fillna(value='S')

In [132]:
def impute(cols):
    Age=cols[0]
    Pclass=cols[1]
    if pd.isnull(Age):
        if Pclass==1:
            return 37
        elif Pclass==2:
            return 29
        else:
            return 24
    else:
        return Age

In [133]:
dataset['Age']=dataset[['Age','Pclass']].apply(impute,axis=1)


In [134]:
dataset_2['Age']=dataset[['Age','Pclass']].apply(impute,axis=1)


In [135]:
X=dataset.iloc[:,[2,4,5,6,7,9,11]].values
X.shape

(891, 7)

In [136]:
X

array([[3, 'male', 22.0, ..., 0, 7.25, 'S'],
       [1, 'female', 38.0, ..., 0, 71.2833, 'C'],
       [3, 'female', 26.0, ..., 0, 7.925, 'S'],
       ..., 
       [3, 'female', 24.0, ..., 2, 23.45, 'S'],
       [1, 'male', 26.0, ..., 0, 30.0, 'C'],
       [3, 'male', 32.0, ..., 0, 7.75, 'Q']], dtype=object)

In [137]:

y=dataset.iloc[:,1].values
y.shape

(891,)

In [138]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [139]:
X_label_1=LabelEncoder()
X_label_2=LabelEncoder()

In [140]:
X[:,6]=X_label_1.fit_transform(X[:,6])
X[:,1]=X_label_1.fit_transform(X[:,1])

In [141]:
one_hot=OneHotEncoder(categorical_features=[1,6])


In [142]:
X=one_hot.fit_transform(X).toarray()


In [143]:
X.shape

(891, 10)

In [101]:
l=pd.DataFrame(X)

In [102]:
l.head()

0    1    2    3    4    5     6    7    8        9
0  0.0  1.0  0.0  0.0  1.0  3.0  22.0  1.0  0.0   7.2500
1  1.0  0.0  1.0  0.0  0.0  1.0  38.0  1.0  0.0  71.2833
2  1.0  0.0  0.0  0.0  1.0  3.0  26.0  0.0  0.0   7.9250
3  1.0  0.0  0.0  0.0  1.0  1.0  35.0  1.0  0.0  53.1000
4  0.0  1.0  0.0  0.0  1.0  3.0  35.0  0.0  0.0   8.0500

In [164]:
X=X[:,[1,3,4,5,6,7,8,9]]

In [165]:
X.shape

(891, 8)

In [26]:
from sklearn.model_selection import train_test_split


In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


In [105]:
from sklearn.ensemble import RandomForestClassifier


In [ ]:
from sklearn

In [166]:
classifier=RandomForestClassifier(n_estimators=20,random_state=0,criterion='entropy')


In [167]:
classifier.fit(X,y)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [31]:
y_pred=classifier.predict(X_test)


In [32]:
print('Accuracy is ',classifier.score(X_test,y_test))


Accuracy is  0.821229050279


In [33]:
dataset_2.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  22.0      0      0   330911   7.8292   NaN        S  
1  38.0      1      0   363272   7.0000   NaN        C  
2  26.0      0      0   240276   9.6875   NaN        S  
3  35.0      0      0   315154   8.6625   NaN        S  
4  35.0      1      1  3101298  12.2875   NaN        S

In [147]:
X_label_test_1=LabelEncoder()
X_label_test_2=LabelEncoder()

In [148]:
dataset_2.iloc[:,10].isnull().values.any()

False

In [150]:
x_new=dataset_2.iloc[:,[1,3,4,5,6,8,10]].values

In [151]:
x_new.shape

(418, 7)

In [59]:
new=pd.DataFrame(x_new)
new.head()

0    1    2    3    4    5     6    7    8        9
0  0.0  1.0  0.0  0.0  1.0  3.0  22.0  0.0  0.0   7.8292
1  1.0  0.0  1.0  0.0  0.0  3.0  38.0  1.0  0.0   7.0000
2  0.0  1.0  0.0  0.0  1.0  2.0  26.0  0.0  0.0   9.6875
3  0.0  1.0  0.0  0.0  1.0  3.0  35.0  0.0  0.0   8.6625
4  1.0  0.0  0.0  0.0  1.0  3.0  35.0  1.0  1.0  12.2875

In [152]:
x_new[:,6]=X_label_test_1.fit_transform(x_new[:,6])
x_new[:,1]=X_label_test_2.fit_transform(x_new[:,1])

In [153]:
one_hot_2=OneHotEncoder(categorical_features=[1,6])


In [154]:
x_new=one_hot_2.fit_transform(x_new).toarray()


In [75]:
new.isnull().values.any()

False

In [149]:
dataset_2.iloc[:,8]=dataset_2.iloc[:,8].fillna(value=11.00)                

In [77]:
x_new=new.iloc[:,[0,1,2,3,4,5,6]].values

In [161]:
x_new=x_new[:,[1,3,4,5,6,7,8,9]]

In [162]:
x_new.shape

(418, 8)

In [168]:
y_pred_test=classifier.predict(x_new)

In [171]:
y_pred_test

array([0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

In [180]:
df1=pd.DataFrame(y_pred_test,dataset_2['PassengerId'])

In [170]:
df1.head()

0
PassengerId   
892          0
893          0
894          0
895          0
896          1

In [172]:
df1.to_csv('submit_6.csv',sep=',')

In [72]:
result=pd.concat(frame)

In [76]:
from numpy.random import randn

In [77]:
last.shape

(418, 1)

In [78]:
last_2.shape

(418, 1)

In [173]:
from sklearn.linear_model import LogisticRegression

In [174]:
cl=LogisticRegression(random_state=0)

In [175]:
cl.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [176]:
y_pred_2=cl.predict(x_new)

In [177]:
y_pred_2

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

In [179]:
df2=pd.DataFrame(y_pred_2,dataset_2['PassengerId'])

In [181]:
df2.to_csv('submit_7.csv',sep=',')