In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

In [3]:
dataset=pd.read_csv('spam.csv',encoding='latin-1')

In [4]:
dataset=dataset.iloc[:,:2]

In [6]:
dataset.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
import re

In [8]:
import nltk

In [9]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/dhama/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
from nltk.corpus import stopwords

In [11]:
from nltk.stem.porter import PorterStemmer

In [12]:
ps=PorterStemmer()

In [13]:
corpus=[]
for i in range(0,5572):
    review=re.sub('[^a-zA-Z0-9]',' ',dataset['v2'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv=CountVectorizer(max_features=4000)

In [16]:
X=cv.fit_transform(corpus).toarray()

In [17]:
X.shape

(5572, 4000)

In [18]:
y=dataset.iloc[:,:1].values

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
lb=LabelEncoder()

In [21]:
y=lb.fit_transform(y)

/home/dhama/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
gb=GaussianNB()

In [27]:
gb.fit(X_train,y_train)

GaussianNB(priors=None)

In [28]:
y_pred=gb.predict(X_test)

In [29]:
gb.score(X_test,y_test)

0.87724335965542

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
cm=confusion_matrix(y_test,y_pred)

In [32]:
cm

array([[1047,  149],
       [  22,  175]])

In [33]:
1047+175

1222

In [34]:
1047+149+22+175

1393

In [35]:
1222/1393

0.87724335965542

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
rf=RandomForestClassifier(n_estimators=20,random_state=0)

In [38]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [39]:
y_2=rf.predict(X_test)

In [40]:
rf.score(X_test,y_test)

0.97702799712849964

In [41]:
cm_new=confusion_matrix(y_test,y_2)

In [42]:
cm_new

array([[1195,    1],
       [  31,  166]])